---
- hosts: my_vm
  remote_user: root

  name: Basic setup
  roles:
    - { role: rpm-repo, tags: repo }
    - network
    - system
    - services
    - { role: vmware-tools, tags: vmtools }

  post_tasks:
    - name: Reboot host
      command: /sbin/shutdown -r now
