---
- command: /usr/sbin/setenforce 0
  ignore_errors: yes

- name: Desabilita SELinux
  selinux: state=disabled

- name: Install system management tool
  yum: name={{ item }} state=present
  with_items:
    - strace
    - nc
    - bind-utils
    - lsof
    - mlocate
    - vim
  ignore_errors: yes

# - include: vmwaretools.yml
