---
- file: state=absent path=/etc/yum.repos.d/{{ item }}
  with_items:
    - CentOS-Base.repo
    - CentOS-Debuginfo.repo
    - CentOS-Media.repo
    - CentOS-Vault.repo
    - CentOS-Testing.repo

- name: Create local CentOS repository file
  copy: src=etc_yum.repos.d_sefa.repo dest=/etc/yum.repos.d/sefa.repo
          owner=root group=root mode=0644

- name: Install yum-utils package
  yum: name=yum-utils state=present disablerepo=* enablerepo=sefa*
  when: ansible_distribution_major_version >= "6"
  ignore_errors: yes

- name: Configure the local repository
  command: /usr/bin/yum-config-manager --enable {{ item }}
  with_items:
    - sefa-base
    - sefa-updates
    - sefa-centosplus
    - sefa-contrib
    - sefa-cr
    - sefa-extras
    - sefa-fasttrack
  when: ansible_distribution_major_version >= "6"
  ignore_errors: yes
