---

  - name: Configure /etc/sysconfig/network file
    template: src=etc_sysconfig_network.j2
              dest=/etc/sysconfig/network

  - name: Configure /etc/sysconfig/network-scripts/ifcfg-ethX file
    template: src=etc_sysconfig_network-scripts_ifcfg-ethX.j2
              dest=/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}

  - name: Ensure network is up
    service: name=network state=started enabled=yes

  - name: Configure /etc/hosts file
    template: src=etc_hosts.j2
              dest=/etc/hosts

  - name: Configure /etc/resolv.conf file
    template: src=etc_resolv.conf.j2
              dest=/etc/resolv.conf
